### ISSUE TITLE
Typo? browse() appears insterad of browser()

### ISSUE THREAD

**Issue by RickPack** [ajmcoqui/debuggingRStudio#1]
Am I correct that `browse()` is a typo when you meant to have `browser()` in the PDF, at the top of the bottom-left box?

**Comment by ajmcoqui** [comment]
You are correct!  I pulled that bottom-left box from the IDE cheatsheet, so I'll ask the owner to update it.  I'll rev the PDF as soon as that change is available. Nicely spotted!

**Comment by ajmcoqui** [comment]
Fixed.
